language: android
jdk:
    - oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-24
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support
script:
    - ./gradlew clean assembleDebug
notifications:
  email:
    recipients:
      - foreverhgx@gmail
    on_success: never
    on_failure: always